version: '2'

services:
    website:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            "run:app"
        environment:
            PYTHONUNBUFFERED: 'true'
        volumes:
            - '.:/app'
        ports:
            - '8000:8000'
